### PR TITLE
Fix build on VS 2015.

### PR DESCRIPTION
**Pull request by Stinkfist0**

### CODE REVIEW

**Comment by Stinkfist0** [comment]
Hi. I'd guess this can be closed if the current master builds now with VS 2015. Haven't tested the master yet though.

**Comment by Stinkfist0** [comment]
ping @QbProg

**Comment by QbProg** [comment]
yes, the master should build now with VS2015. Could you just build oce + bundle (using the new automatic build system) and let me know?
Basically, just put oce-win-bundle inside the oce source directory and clean configure and build.

**Comment by Stinkfist0** [comment]
Seems OK now.

**Pull request closed without merging**
