### PR TITLE
BUNDLE_USE_STATIC_MSVC_RUNTIME build option

### PR DESCRIPTION
**Pull request by Stinkfist0**
Build option to generate code using the static MSVC run-time instead of the DLL (the default behavior of CMake). This is useful when building an application executable that uses OCE and oce-win-bundle and not wanting to depend on the end-user to install the right version of Microsoft Visual C++ Redistributable for Visual Studio XXXX.

### CODE REVIEW

**Comment by Stinkfist0** [comment]
OCE counterpart: https://github.com/tpaviot/oce/pull/577

**Comment by Stinkfist0** [comment]
Hi. What's the status on this? I (and others) have been using this happily for couple months now with OCE & IfcOpenShell.

**Comment by QbProg** [comment]
now that the change is merged in OCE, ihmo it should be working automatically also in the bundle libraries *without* this commit (as these are using the same compilation options as OCE).
could you please test that? 
If not I will accept the change.

**Comment by Stinkfist0** [comment]
Testing now and will report back soon.

**Comment by Stinkfist0** [comment]
Everything seems to be in order!

**Pull request closed without merging**
